# 2.3.1  Numpy数组
直接使用python列表

In [70]:
import numpy as np
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

查看array属性,包括数据唯独和类型

In [7]:
b.ndim  #维度

2

In [8]:
b.shape   #维度

(3, 2)

In [9]:
b.dtype #类型

dtype('int32')

## 1.使用numpy的函数创建数组

In [11]:
c=np.arange(10)  #连续数组
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
d =np.linspace(0,2,11)  #0 2 之间11等分
d

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [14]:
np.random.randn(6,4)   #6*4随机数组

array([[-0.10654479,  0.24191912,  1.59645196, -1.52104493],
       [ 0.52319478, -0.1250676 ,  1.69615251,  0.16194233],
       [ 1.34476185, -1.25579653, -0.35745584,  0.62139423],
       [-1.5152939 ,  0.5818791 , -0.63471078,  1.3878522 ],
       [ 0.65045596,  0.46459719,  1.0641216 , -0.4639022 ],
       [-0.99445137, -1.80194905, -0.10520724,  0.25816973]])

## `2.通过索引机制访问数组内的元素`重要

In [32]:
a=np.arange(10)
a[0],a[2]

(0, 2)

In [19]:
a[:8]  #半开区间，不包括8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
a[1:7]

array([1, 2, 3, 4, 5, 6])

In [22]:
a[8:]

array([8, 9])

In [23]:
a[2:8:3]  #起始终止步长，不包括8

array([2, 5])

In [25]:
a[2::3] #可不要终止位置

array([0, 3, 6, 9])

In [26]:
a[::3]  

array([0, 3, 6, 9])

## 3.二维数据分成行列两个维度，可以更灵活,练习2的内容

In [39]:
# 创建一个6*6的二维数组，使用广播机制,后面会有解释
a=np.arange(0,51,10).reshape(6,1)+np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [29]:
a[0,0],a[1,0],a[2,0],a[2,-1]   # 二维数组取值方式

(0, 10, 20, 25)

In [31]:
a[0,2:5]   # 上面的内容，通过索引机制访问数组内的元素

array([2, 3, 4])

In [41]:
a[0:3,2:4]   # 截取其中一部分数组

array([[ 2,  3],
       [12, 13],
       [22, 23]])

In [42]:
a[:3,4]

array([ 4, 14, 24])

In [43]:
a[:3,:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
a #再显示一遍

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [45]:
a[2,:]   #获取行

array([20, 21, 22, 23, 24, 25])

In [46]:
a[:,2]  # 获取列，但是Numpy自动转换成行的向量形式

array([ 2, 12, 22, 32, 42, 52])

In [49]:
a[2,::2]    #练习步长法获取数据

array([20, 22, 24])

In [50]:
a[::2,::2]  #步长获取

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

另一个索引的方法是通过布尔数组

In [52]:
a=np.random.randint(10,20,6) #在10 20之间产生6个随机数
a


array([16, 14, 13, 19, 19, 16])

In [53]:
a%2==0

array([ True,  True, False, False, False,  True])

In [54]:
a[a%2==0]  # 通过bool类型获取索引的值

array([16, 14, 16])

In [60]:
a=np.arange(0,51,10).reshape(6,1) #创建一个数组，从0到51，步长为10.将这个数组的维度变成6*1的数组
b=np.arange(6)  #这也就解释了a=np.arange(0,51,10).reshape(6,1)+np.arange(6)，行列式相加
a,b,a+b,a*b  

(array([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50]]),
 array([0, 1, 2, 3, 4, 5]),
 array([[ 0,  1,  2,  3,  4,  5],
        [10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35],
        [40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55]]),
 array([[  0,   0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40,  50],
        [  0,  20,  40,  60,  80, 100],
        [  0,  30,  60,  90, 120, 150],
        [  0,  40,  80, 120, 160, 200],
        [  0,  50, 100, 150, 200, 250]]))

一个需要注意的点是，numpy会将结果自动转换成行向量，比如下面的例子，对a+b的数组进行布尔索引时，结果变成一个行向量

In [61]:
(a+b)[(a+b)%2==0]  # 也就是a=np.arange(0,51,10).reshape(6,1)+np.arange(6)，对于这个数组，获取偶数，和0

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44, 50, 52,
       54])

另外需要注意的是，大部分情况下，numpy数组共享内存，如果要独立保存，需要显式地备份。可以使用np.may_share_memory()函数判断两数组是否共享内存

In [75]:
a=np.arange(6)
b=a[2:5]
'a',a,'b',b

('a', array([0, 1, 2, 3, 4, 5]), 'b', array([2, 3, 4]))

In [78]:
b[1]=200  #可以看到，改变b的值，a,b的值都变了
a,b 

(array([  0,   1,   2, 200,   4,   5]), array([  2, 200,   4]))

In [80]:
np.may_share_memory (a,b)

True

In [87]:
b=a[2:5].copy() # 显式地备份
a,b

(array([  0,   1,   2, 200,   4,   5]), array([  2, 200,   4]))

In [88]:
b[1]=100  # 可以看到，使用copy后再改变值就不会两个同时改变
a[2:5],b  

(array([  2, 200,   4]), array([  2, 100,   4]))